Add Amazon MSK event structure
aws/aws-lambda-go pull request #316
Opened 2020-08-19 19:24 UTC by ewbankkit

Closes https://github.com/aws/aws-lambda-go/issues/315.

Adds Amazon MSK event structures.

```console
$ go test ./events/
ok  	github.com/aws/aws-lambda-go/events	0.020s
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-22 18:42 UTC, bmoffatt requested changes

2020-09-22 18:42 UTC, bmoffatt commented on events/msk.go
> +type MskEvent struct {
capitalize as `MSKEvent`

2020-09-22 18:42 UTC, bmoffatt commented on events/msk.go
> +type MskRecord struct {
rename `MSKEventRecord`

2020-09-22 18:42 UTC, bmoffatt commented on events/msk.go
> +// Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
2020, to match file creation date

2020-09-22 18:42 UTC, bmoffatt commented on events/msk_test.go
> +// Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
2020, to match file creation date

2020-09-22 18:43 UTC, bmoffatt commented
@carlzogh should we name this `KafaEvent` instead to match the java library?

ref: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KafkaEvent.java

2020-09-24 21:56 UTC, carlzogh commented
> @carlzogh should we name this `KafaEvent` instead to match the java library?
> 
> ref: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KafkaEvent.java

Yes I think we should name it `KafkaEvent` to stay consistent.

2020-09-27 20:21 UTC, ewbankkit commented
Renaming done.

2020-10-03 00:39 UTC, bmoffatt approved these changes

2020-10-03 00:39 UTC, merged