Lambda direct resolver event type
aws/aws-lambda-go pull request #465
Opened 2022-08-26 01:13 UTC by joshpauline

Adding lambda direct resolver request event to be used in cased where we are not using direct vtl integrations and require to be able to handle the event in a lambda. I have used this same event for months in production and it has worked out great.

2022-08-29 23:12 UTC, joshpauline commented
I added another test but the code coverage is not passing. Could anyone let me know why so I can amend the tests.

2022-08-30 01:05 UTC, bmoffatt commented
The coverage is fine - its the linter check that's failing

> events/appsync.go:69: File is not `gofmt`-ed with `-s` (gofmt)

2022-08-30 01:19 UTC, bmoffatt commented
Also, got a link to the AWS docs for this integration that I can use as a reference for reviewing this PR?

2022-08-30 01:23 UTC, joshpauline commented
> The coverage is fine - its the linter check that's failing
> 
> > events/appsync.go:69: File is not `gofmt`-ed with `-s` (gofmt)

Thank you @bmoffatt, sorry I was readying the actions wrong. 

I am not getting an error when I run gofmt -s -w . on the directory. Can you see anything that I am doing wrong?

2022-08-30 01:37 UTC, joshpauline commented
@bmoffatt here is a link to the direct lambda resolver docs

https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html

Note that some types need to be map[string]interface{} because there are many different options, such as `identity`

2022-09-26 22:24 UTC, bmoffatt requested changes

2022-09-26 22:24 UTC, bmoffatt commented on events/appsync.go
> +		}
seems that `Headers` should be `map[string]string` instead of a struct. doc link says custom client headers are passed here too

2022-09-26 22:24 UTC, bmoffatt commented on events/appsync.go
> +	}
missing `json:"info"`

2022-09-26 22:24 UTC, bmoffatt commented on events/appsync.go
> +	}
missing `json:"request"`

2022-09-26 22:24 UTC, bmoffatt commented on events/appsync.go
> +		SelectionSetList    []string `json:"selectionSetList"`
missing `"variables"` field from the doc link

2022-09-26 22:24 UTC, bmoffatt commented on events/appsync.go
> +	Prev    string `json:"prev"`
docs you linked imply this one has a sub-field "result"

2022-11-16 20:18 UTC, bmoffatt commented
@joshpauline do you plan to continue this one? #467 has been opened to add the same struct

2022-11-17 00:20 UTC, closed without merging