[479] CloudWatchEvent renamed to EventBridgeEvent
aws/aws-lambda-go pull request #537
Opened 2023-12-17 17:26 UTC by mateusmarquezini

*Issue #479*

*Description of changes:*

Hi there! This should fix #479. Please, let me know if you meant something else! 

Besides having renamed from CloudWatchEvent to EventBridgeEvent on some places of the code base, I also updated some links (despite they're still redirecting correctly)

Looking forward to your feedback! Thanks! :)

2023-12-19 21:30 UTC, bmoffatt requested changes

2023-12-19 21:30 UTC, bmoffatt commented on events/cloudwatch_events.go
> -type CloudWatchEvent struct {
Renaming the type is a breaking change. Adding a type alias `type EventBridgeEvent = CloudWatchEvent` would be required to not break existing consumers

2023-12-19 21:30 UTC, bmoffatt commented on events/cloudwatch_logs.go
> -// CloudwatchLogsEvent represents raw data from a cloudwatch logs event
CloudWatch Events (now named Event Bridge) is distinct from CloudWatch Logs (still called CloudWatch!)

A find/replace of CloudWatch -> EventBridge isn't the way to go about this documentation refresh

2023-12-19 21:30 UTC, bmoffatt commented on events/codepipeline_cloudwatch.go
> +type CodePipelineEventBridgeEvent struct {
requires a type alias to not break existing consumers

2023-12-19 21:30 UTC, bmoffatt commented on events/codepipeline_cloudwatch.go
> +// https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-service-event.html#codepipeline_event_type
The content is different than what it was when it was added in the first place. May as well remove the link if there's not an equivalent anymore

2023-12-19 22:46 UTC, mateusmarquezini commented
Thank you for taking the time to suggest improvements @bmoffatt! I just made some changes as you suggested. Now it is as it should I guess. Let me know if it still needs more changes.

2023-12-22 00:06 UTC, bmoffatt requested changes

2023-12-22 00:06 UTC, bmoffatt commented on events/cloudwatch_events.go
> +type EventBridge = CloudWatchEvent
`EventBridgeEvent`

2023-12-22 00:06 UTC, bmoffatt commented on events/README_CloudWatch_Events.md
should rename this file too, README_EventBridge_Events.md

2023-12-23 00:33 UTC, bmoffatt requested changes

2023-12-23 00:33 UTC, bmoffatt commented on events/cloudwatch_logs_test.go
> +		expectEventBridgeData CloudwatchLogsEvent
revert the changes to this test file, it's for CloudWatch Logs, not EventBridge

2024-01-04 23:26 UTC, bmoffatt approved these changes

2024-01-04 23:26 UTC, merged